server:
  port: 4377
  servlet:
    context-path: /data-import
    
spring:
  servlet:
    multipart:
      maxFileSize: 2000MB
      maxRequestSize: 2000MB
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

        
    